apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: create-topics
  name: create-topics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-topics
  template:
    metadata:
      labels:
        app: create-topics
    spec:
      containers:
      - image: andyaz/create-topics:latest
        name: create-topics

