services:

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka-broker-1:
        container_name: broker_1
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        ports:
            - 19092:19092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker_1:9092,PLAINTEXT_HOST://localhost:19092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
        volumes:
            - ./create_topics.sh:/etc/kafka/create_topics.sh

    kafka-broker-2:
        container_name: broker_2
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        ports:
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker_2:9093,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

    kafka-broker-3:
        container_name: broker_3
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        ports:
            - 39092:39092
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker_3:9094,PLAINTEXT_HOST://localhost:39092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
        #--------------------------------------------------------------------------------------------------------
    db:
        build:
            context: .
            dockerfile: Dockerfile-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: hw1
            MYSQL_USER: andrea
            MYSQL_PASSWORD: password
        volumes:
            - hw1_volume:/var/lib/mysql
        container_name: hw1_db_container
        ports:
            - 3306:3306

volumes:
    hw1_volume:
        driver: local
