services:
    db:
        build:
            context: .
            dockerfile: Dockerfile-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: hw1
            MYSQL_USER: andrea
            MYSQL_PASSWORD: password
        ports: 
          - 3306:3306
        volumes:
            - hw1_volume:/var/lib/mysql
        container_name: hw1_db_container

    db_client: #Solo per il testing del DB
        build:
            context: .
            dockerfile: Dockerfile-ubuntuclient
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_HOST=mysqldb
            - MYSQL_USER=andrea
            - MYSQL_PASSWORD=password
            - MYSQL_PORT= 3306
        depends_on:
            - db
        container_name: hw1_db_client_container
        stdin_open: true  # Mantiene lo standard input aperto
        tty: true         # Avvia con un terminale virtuale
        restart: always
        
    
    
volumes: 
    hw1_volume: