services:
    db:
        build:
            context: .
            dockerfile: Dockerfile-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: hw1
            MYSQL_USER: andrea
            MYSQL_PASSWORD: password
        volumes:
            - hw1_volume:/var/lib/mysql
        container_name: hw1_db_container
        ports:
            - 3306:3306

volumes:
    hw1_volume:
        driver: local
