FROM python:3.13

WORKDIR /app

COPY circuit_breaker.py /app/
COPY data_collector.py /app/
COPY cqrs_data_collector.py /app/
COPY open_db_connection.py /app/

RUN pip install yfinance mysql-connector-python

CMD python data_collector.py
