FROM python:3.9

VOLUME /app

COPY client.py /app/
COPY calc_pb2_grpc.py /app/
COPY calc_pb2.py /app/
COPY calc_pb2.pyi /app/

#ENTRYPOINT ["/bin/sh"]
RUN pip install grpcio grpcio-tools google-api-python-client
CMD python app/client.py
