FROM python:3.13

WORKDIR /app
EXPOSE 50051

COPY server.py /app/
COPY hw1_pb2_grpc.py /app/
COPY hw1_pb2.py /app/
COPY hw1_pb2.pyi /app/

RUN pip install grpcio grpcio-tools google-api-python-client mysql-connector-python
CMD python server.py


