FROM python:3.9

VOLUME /app
EXPOSE 50051

COPY server.py /app/
COPY echo_pb2_grpc.py /app/
COPY echo_pb2.py /app/
COPY echo_pb2.pyi /app/

RUN pip install grpcio grpcio-tools google-api-python-client mysql-connector-python
CMD python app/server.py

#attenzione!
#avviare il container con -i -t
# specificare il nome del volume o del path di bind mounth
# specificare il port mapping <host port>:50051
