# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hw1_pb2 as hw1__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hw1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManageUserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterMessage = channel.unary_unary(
                '/hw1.ManageUser/RegisterMessage',
                request_serializer=hw1__pb2.Register.SerializeToString,
                response_deserializer=hw1__pb2.Reply.FromString,
                _registered_method=True)
        self.UpdateMessage = channel.unary_unary(
                '/hw1.ManageUser/UpdateMessage',
                request_serializer=hw1__pb2.Update.SerializeToString,
                response_deserializer=hw1__pb2.Reply.FromString,
                _registered_method=True)
        self.DeleteMessage = channel.unary_unary(
                '/hw1.ManageUser/DeleteMessage',
                request_serializer=hw1__pb2.Delete.SerializeToString,
                response_deserializer=hw1__pb2.Reply.FromString,
                _registered_method=True)


class ManageUserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManageUserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterMessage,
                    request_deserializer=hw1__pb2.Register.FromString,
                    response_serializer=hw1__pb2.Reply.SerializeToString,
            ),
            'UpdateMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMessage,
                    request_deserializer=hw1__pb2.Update.FromString,
                    response_serializer=hw1__pb2.Reply.SerializeToString,
            ),
            'DeleteMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMessage,
                    request_deserializer=hw1__pb2.Delete.FromString,
                    response_serializer=hw1__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hw1.ManageUser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hw1.ManageUser', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManageUser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hw1.ManageUser/RegisterMessage',
            hw1__pb2.Register.SerializeToString,
            hw1__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hw1.ManageUser/UpdateMessage',
            hw1__pb2.Update.SerializeToString,
            hw1__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hw1.ManageUser/DeleteMessage',
            hw1__pb2.Delete.SerializeToString,
            hw1__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StockServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getLastStockValue = channel.unary_unary(
                '/hw1.StockService/getLastStockValue',
                request_serializer=hw1__pb2.GetLastStockValueRequest.SerializeToString,
                response_deserializer=hw1__pb2.GetLastStockValueResponse.FromString,
                _registered_method=True)
        self.getStockPriceAverage = channel.unary_unary(
                '/hw1.StockService/getStockPriceAverage',
                request_serializer=hw1__pb2.GetStockPriceAverageRequest.SerializeToString,
                response_deserializer=hw1__pb2.GetStockPriceAverageResponse.FromString,
                _registered_method=True)


class StockServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getLastStockValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getStockPriceAverage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getLastStockValue': grpc.unary_unary_rpc_method_handler(
                    servicer.getLastStockValue,
                    request_deserializer=hw1__pb2.GetLastStockValueRequest.FromString,
                    response_serializer=hw1__pb2.GetLastStockValueResponse.SerializeToString,
            ),
            'getStockPriceAverage': grpc.unary_unary_rpc_method_handler(
                    servicer.getStockPriceAverage,
                    request_deserializer=hw1__pb2.GetStockPriceAverageRequest.FromString,
                    response_serializer=hw1__pb2.GetStockPriceAverageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hw1.StockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hw1.StockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StockService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getLastStockValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hw1.StockService/getLastStockValue',
            hw1__pb2.GetLastStockValueRequest.SerializeToString,
            hw1__pb2.GetLastStockValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getStockPriceAverage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hw1.StockService/getStockPriceAverage',
            hw1__pb2.GetStockPriceAverageRequest.SerializeToString,
            hw1__pb2.GetStockPriceAverageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
