apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alert-system
  name: alert-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-system
  template:
    metadata:
      labels:
        app: alert-system
    spec:
      containers:
      - image: andyaz/alert-system:latest
        name: alert-system
      initContainers:
        - name: init-container
          image: busybox
          command: ['sh', '-c', 'until nc -zv create-topics 2222; do echo "Waiting for create-topics..."; sleep 2; done']

