apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: create-topics
  name: create-topics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-topics
  template:
    metadata:
      labels:
        app: create-topics
    spec:
      containers:
      - image: andyaz/create-topics:latest
        imagePullPolicy: Always
        name: create-topics
        ports:
        - containerPort: 2222
          name: create-topics
      initContainers:
      - name: init-container-1
        image: busybox
        command: ['sh', '-c', 'until nc -zv broker-1 9092; do echo "Waiting for broker 1..."; sleep 2; done']
      - name: init-container-2
        image: busybox
        command: ['sh', '-c', 'until nc -zv broker-2 9093; do echo "Waiting for broker 2..."; sleep 2; done']
      - name: init-container-3
        image: busybox
        command: ['sh', '-c', 'until nc -zv broker-3 9094; do echo "Waiting for broker 3..."; sleep 2; done']

