apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-collector
  name: data-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
    spec:
      containers:
      - image: andyaz/data-collector:latest
        name: data-collector
        ports:
        - containerPort: 7777
          name: data-collector

