apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-collector
  name: data-collector
spec:
  type: ClusterIP
  ports:
  - name: "data-collector-service"
    port: 7777
    targetPort: 7777
  selector:
    app: data-collector

