apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-collector
  name: data-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
    spec:
      containers:
      - image: andyaz/data-collector:latest
        name: data-collector
        ports:
        - containerPort: 7777
          name: data-collector
      initContainers:
        - name: init-container
          image: busybox
          command: ['sh', '-c', 'until nc -zv create-topics 2222; do echo "Waiting for create-topics..."; sleep 2; done']

